using System.Text.Json;
using PFA_FVG_Scanner.Data;
using PFA_FVG_Scanner.Domain.Forward;
using PFA_FVG_Scanner.Domain.Governance;
using PFA_FVG_Scanner.Domain.Sandbox;
using PFA_FVG_Scanner.Domain.Validation;

namespace PFA_FVG_Scanner.Services;

public interface IForwardHealthProvider{ForwardHealthSample Capture(string campaignId,DateTime sampledAtUtc,int intervalSeconds);}
public sealed class WatchdogForwardHealthProvider: IForwardHealthProvider
{
    private readonly MarketDataWatchdogService _watchdog;private readonly MarketData.IMarketDataProvider _provider;public WatchdogForwardHealthProvider(MarketDataWatchdogService watchdog,MarketData.IMarketDataProvider provider){_watchdog=watchdog;_provider=provider;}
    public ForwardHealthSample Capture(string campaignId,DateTime sampledAtUtc,int intervalSeconds){var unix=new DateTimeOffset(sampledAtUtc).ToUnixTimeSeconds();var bucketUnix=unix-unix%intervalSeconds;var bucket=DateTimeOffset.FromUnixTimeSeconds(bucketUnix).UtcDateTime;var identity=JsonSerializer.Serialize(new{campaignId,bucket,_watchdog.IsFeedHealthy,_watchdog.IsFeedStale,_provider.ConnectionState.LastCandleReceivedUtc,_watchdog.LastHealthCheckUtc,_watchdog.LastReconnectAttemptUtc,_watchdog.HealthMessage});var hash=ForwardHash.Of(identity);return new($"FWH-{hash[..32]}",campaignId,bucket,_watchdog.IsFeedHealthy,_watchdog.IsFeedStale,_provider.ConnectionState.LastCandleReceivedUtc,_watchdog.LastHealthCheckUtc,_watchdog.LastReconnectAttemptUtc,_watchdog.HealthMessage,hash);}
}

public sealed record ForwardCaptureResult(ForwardDailySnapshot Snapshot,ForwardComparison? Comparison,bool SuspendedAutomatically);

public sealed class ForwardCampaignService
{
    private readonly ForwardCampaignRepository _repository;private readonly IWalkForwardValidationRepository _validation;private readonly SandboxService _sandbox;private readonly GovernanceRepository _governance;private readonly ForwardExpectationComparator _comparator;private readonly IForwardHealthProvider _health;private readonly ISandboxClock _clock;
    public ForwardCampaignService(ForwardCampaignRepository repository,IWalkForwardValidationRepository validation,SandboxService sandbox,GovernanceRepository governance,ForwardExpectationComparator comparator,IForwardHealthProvider health,ISandboxClock clock){_repository=repository;_validation=validation;_sandbox=sandbox;_governance=governance;_comparator=comparator;_health=health;_clock=clock;}
    public async Task<ForwardCampaign> CreateAsync(string accountId,string instanceId,ForwardExpectation expectation,string actor,CancellationToken token=default)
    {
        expectation.Validate();var report=await _validation.FindReportAsync(expectation.SourceReportId,token)??throw new KeyNotFoundException("Walk-forward source report was not found.");if(report.ContentHash!=expectation.SourceContentHash||report.Status!=WalkForwardAggregateStatus.Stable||report.CanActivateStrategy)throw new UnauthorizedAccessException("Forward campaigns require an exact stable non-activating walk-forward report.");var weightedWinRate=report.Folds.Sum(x=>x.WinRate*x.Samples)/Math.Max(1,report.Folds.Sum(x=>x.Samples));var maxDrawdown=report.Folds.Max(x=>x.MaximumDrawdownR);if(expectation.HistoricalExpectancyR!=report.WeightedExpectancyR||expectation.HistoricalWinRate!=weightedWinRate||expectation.HistoricalMaximumDrawdownR!=maxDrawdown)throw new InvalidOperationException("Frozen expectations must exactly match the source report metrics.");var account=await _sandbox.GetAccountAsync(accountId,token);if(!account.Instances.TryGetValue(instanceId,out var instance))throw new KeyNotFoundException("Sandbox instance was not found.");if(instance.StrategyId!=expectation.StrategyId||instance.StrategyVersion!=expectation.StrategyVersion)throw new InvalidOperationException("Forward expectation and sandbox strategy version do not match.");var identity=JsonSerializer.Serialize(new{accountId,instanceId,expectation.ExpectationId,ExpectationHash=expectation.ContentHash()});var id=$"FWP-{ForwardHash.Of(identity)[..32]}";var campaign=new ForwardCampaign(id,accountId,instanceId,instance.StrategyId,instance.StrategyVersion,expectation,ForwardCampaignStatus.Created,_clock.UtcNow,null,null,"campaign-created",actor,false);await _repository.CreateAsync(campaign,token);return(await _repository.FindAsync(id,token))!;
    }
    public async Task<ForwardCampaign> StartAsync(string campaignId,string actor,string reason,CancellationToken token=default)
    {var campaign=await Campaign(campaignId,token);if(campaign.Status!=ForwardCampaignStatus.Created)throw new InvalidOperationException("Only a created forward campaign can start.");var state=await _sandbox.GetAccountAsync(campaign.AccountId,token);if(!state.Instances.TryGetValue(campaign.InstanceId,out var instance)||instance.Status!=SandboxInstanceStatus.Running)throw new InvalidOperationException("The sandbox instance must be running.");var policy=await _governance.GetEffectivePolicyAsync(_clock.UtcNow,token)??throw new UnauthorizedAccessException("An effective governance policy is required.");if((await _governance.GetEmergencyStopAsync(token))?.IsActive==true)throw new UnauthorizedAccessException("The governance emergency stop is active.");var approvals=await _governance.GetApprovalsAsync(token);if(!approvals.Any(x=>x.Scope==GovernanceApprovalScope.Account&&x.ScopeId==campaign.AccountId&&x.PolicyId==policy.PolicyId&&x.PolicyVersion==policy.PolicyVersion&&x.IsActiveAt(_clock.UtcNow))||!approvals.Any(x=>x.Scope==GovernanceApprovalScope.StrategyVersion&&x.ScopeId==$"{campaign.StrategyId}|{campaign.StrategyVersion}"&&x.PolicyId==policy.PolicyId&&x.PolicyVersion==policy.PolicyVersion&&x.IsActiveAt(_clock.UtcNow)))throw new UnauthorizedAccessException("Active account and strategy approvals are required.");await _repository.AppendEventAsync(ForwardCampaignRepository.Event(campaign,"Started",ForwardCampaignStatus.Running,_clock.UtcNow,actor,reason),token);return(await _repository.FindAsync(campaignId,token))!;}
    public async Task<ForwardCampaign> StopAsync(string campaignId,string actor,string reason,CancellationToken token=default){var campaign=await Campaign(campaignId,token);if(campaign.Status is ForwardCampaignStatus.Stopped or ForwardCampaignStatus.Completed)throw new InvalidOperationException("Forward campaign is already terminal.");await _repository.AppendEventAsync(ForwardCampaignRepository.Event(campaign,"Stopped",ForwardCampaignStatus.Stopped,_clock.UtcNow,actor,reason),token);return(await _repository.FindAsync(campaignId,token))!;}
    public async Task<ForwardHealthSample> CaptureHealthAsync(string campaignId,CancellationToken token=default){var campaign=await Campaign(campaignId,token);if(campaign.Status!=ForwardCampaignStatus.Running)throw new InvalidOperationException("Only running campaigns collect health telemetry.");var sample=_health.Capture(campaignId,_clock.UtcNow,campaign.Expectation.HealthSampleIntervalSeconds);await _repository.SaveHealthAsync(sample,token);return sample;}
    public async Task<ForwardCaptureResult> CaptureClosedDayAsync(string campaignId,DateOnly tradingDate,CancellationToken token=default)
    {
        var campaign=await Campaign(campaignId,token);var dayStart=DateTime.SpecifyKind(tradingDate.ToDateTime(TimeOnly.MinValue),DateTimeKind.Utc);var end=dayStart.AddDays(1);var start=campaign.StartedAtUtc.HasValue&&campaign.StartedAtUtc>dayStart?campaign.StartedAtUtc.Value:dayStart;if(start>=end)throw new InvalidOperationException("The campaign was not running during the requested trading date.");if(end>_clock.UtcNow)throw new InvalidOperationException("A forward daily snapshot cannot close before its session window ends.");var existing=(await _repository.GetSnapshotsAsync(campaignId,token)).SingleOrDefault(x=>x.TradingDate==tradingDate);if(existing is not null){var dashboard=await _repository.DashboardAsync(campaignId,token);return new(existing,dashboard!.Comparisons.LastOrDefault(),campaign.Status==ForwardCampaignStatus.Suspended);}
        var state=await _sandbox.GetAccountAsync(campaign.AccountId,token);var trades=state.Trades.Where(x=>x.ClosedAtUtc>=start&&x.ClosedAtUtc<end).OrderBy(x=>x.ClosedAtUtc).ToArray();var fills=state.Fills.Where(x=>x.FilledAtUtc>=start&&x.FilledAtUtc<end).OrderBy(x=>x.FilledAtUtc).ToArray();var gross=trades.Sum(x=>x.GrossProfitLoss);var commissions=fills.Sum(x=>x.Commission);var net=gross-commissions;var expectancy=trades.Length==0?0:net/trades.Length/campaign.Expectation.FixedRiskDollars;var wins=trades.Count(x=>x.NetProfitLoss>0);var losses=trades.Count(x=>x.NetProfitLoss<0);decimal equity=0,peak=0,drawdown=0;foreach(var change in fills.Select(x=>(x.FilledAtUtc,Order:0,Delta:-x.Commission)).Concat(trades.Select(x=>(x.ClosedAtUtc,Order:1,Delta:x.GrossProfitLoss))).OrderBy(x=>x.Item1).ThenBy(x=>x.Order)){equity+=change.Delta;peak=Math.Max(peak,equity);drawdown=Math.Max(drawdown,peak-equity);}var health=await _repository.GetHealthAsync(campaignId,start,end,token);var expectedSamples=Math.Max(1,(int)Math.Ceiling((end-start).TotalSeconds/campaign.Expectation.HealthSampleIntervalSeconds));var healthy=health.Count(x=>x.FeedHealthy&&!x.FeedStale);var coverage=Math.Min(100m,100m*healthy/expectedSamples);var reconnects=health.Where(x=>x.LastReconnectAttemptUtc>=start&&x.LastReconnectAttemptUtc<end).Select(x=>x.LastReconnectAttemptUtc).Distinct().Count();var identity=JsonSerializer.Serialize(new{campaignId,tradingDate,start,end,KnownAt=_clock.UtcNow,trades=trades.Select(x=>x.TradeId).ToArray(),fills=fills.Select(x=>x.FillId).ToArray(),gross,commissions,expectancy,wins,losses,drawdown,Health=health.Select(x=>x.SampleId).ToArray(),coverage,reconnects,state.LastSequence});var hash=ForwardHash.Of(identity);var snapshot=new ForwardDailySnapshot($"FWD-{ForwardHash.Of($"{campaignId}|{tradingDate:yyyy-MM-dd}")[..32]}",campaignId,tradingDate,start,end,_clock.UtcNow,trades.Length,wins,losses,gross,commissions,net,expectancy,trades.Length==0?0:100m*wins/trades.Length,drawdown/campaign.Expectation.FixedRiskDollars,health.Count,healthy,reconnects,coverage,true,$"{campaign.AccountId}|SEQ-{state.LastSequence}",hash,false);await _repository.SaveSnapshotAsync(snapshot,token);var snapshots=await _repository.GetSnapshotsAsync(campaignId,token);var comparison=_comparator.Compare(campaign,snapshots,_clock.UtcNow);await _repository.SaveComparisonAsync(comparison,token);if(comparison.SuspendedAutomatically)await SuspendAutomatically(campaign,comparison,token);return new(snapshot,comparison,comparison.SuspendedAutomatically);
    }
    public Task<ForwardCampaignDashboard?> DashboardAsync(string campaignId,CancellationToken token=default)=>_repository.DashboardAsync(campaignId,token);
    public async Task TickAsync(CancellationToken token=default){foreach(var campaign in await _repository.GetByStatusAsync(ForwardCampaignStatus.Running,token)){await CaptureHealthAsync(campaign.CampaignId,token);var priorDateTime=_clock.UtcNow.AddDays(-1);var prior=DateOnly.FromDateTime(priorDateTime);var priorEnd=DateTime.SpecifyKind(prior.AddDays(1).ToDateTime(TimeOnly.MinValue),DateTimeKind.Utc);if(campaign.StartedAtUtc<priorEnd&&!(await _repository.GetSnapshotsAsync(campaign.CampaignId,token)).Any(x=>x.TradingDate==prior))await CaptureClosedDayAsync(campaign.CampaignId,prior,token);}}
    private async Task SuspendAutomatically(ForwardCampaign campaign,ForwardComparison comparison,CancellationToken token){var now=_clock.UtcNow;var reason=$"{comparison.Status}: {comparison.Summary}";await _repository.AppendEventAsync(ForwardCampaignRepository.Event(campaign,"AutomaticallySuspended",ForwardCampaignStatus.Suspended,now,"forward-monitor",reason),token);var suspension=new GovernanceSuspension($"FWS-{comparison.ComparisonId}",GovernanceSuspensionScope.StrategyVersion,$"{campaign.StrategyId}|{campaign.StrategyVersion}",reason,"forward-monitor",now);await _governance.SuspendAsync(suspension,token);var evidence=JsonSerializer.Serialize(comparison);var hash=ForwardHash.Of(evidence);await _repository.SaveIncidentAsync(new($"FWI-{hash[..32]}",campaign.CampaignId,comparison.SuspensionReason.ToString(),now,reason,evidence,hash),token);await _governance.SaveIncidentAsync(new($"GVI-{hash[..32]}","High","ForwardDegradation",campaign.AccountId,campaign.InstanceId,now,reason,evidence,hash),token);}
    private async Task<ForwardCampaign> Campaign(string id,CancellationToken token)=>await _repository.FindAsync(id,token)??throw new KeyNotFoundException("Forward campaign was not found.");
}

public sealed class ForwardCampaignMonitorService:BackgroundService
{
    private readonly ForwardCampaignService _service;private readonly ILogger<ForwardCampaignMonitorService> _logger;public ForwardCampaignMonitorService(ForwardCampaignService service,ILogger<ForwardCampaignMonitorService> logger){_service=service;_logger=logger;}
    protected override async Task ExecuteAsync(CancellationToken stoppingToken){while(!stoppingToken.IsCancellationRequested){try{await _service.TickAsync(stoppingToken);}catch(OperationCanceledException) when(stoppingToken.IsCancellationRequested){break;}catch(Exception ex){_logger.LogError(ex,"Forward campaign monitor tick failed safely.");}try{await Task.Delay(TimeSpan.FromMinutes(1),stoppingToken);}catch(OperationCanceledException){break;}}}
}
