using System.Security.Cryptography;
using System.Text;
using PFA_FVG_Scanner.Data;
using PFA_FVG_Scanner.Domain.Instruments;
using PFA_FVG_Scanner.Domain.Sandbox;
using PFA_FVG_Scanner.Domain.Strategies;
using PFA_FVG_Scanner.Domain.Governance;

namespace PFA_FVG_Scanner.Services;

public sealed class SandboxService
{
    private readonly SandboxLedgerRepository _ledger;private readonly SandboxStateProjector _projector;private readonly SandboxBrokerSimulator _broker;private readonly SandboxPortfolioProjector _portfolio;private readonly IStrategyRegistry _strategies;private readonly IInstrumentDefinitionRegistry _instruments;private readonly ISandboxClock _clock;private readonly IGovernancePermitValidator _permits;
    public SandboxService(SandboxLedgerRepository ledger,SandboxStateProjector projector,SandboxBrokerSimulator broker,SandboxPortfolioProjector portfolio,IStrategyRegistry strategies,IInstrumentDefinitionRegistry instruments,ISandboxClock clock,IGovernancePermitValidator permits){_ledger=ledger;_projector=projector;_broker=broker;_portfolio=portfolio;_strategies=strategies;_instruments=instruments;_clock=clock;_permits=permits;}
    public async Task<SandboxAccountState> CreateAccountAsync(string commandId,string accountId,string displayName,decimal initialBalance,CancellationToken token=default)
    {Required(commandId,nameof(commandId));Required(accountId,nameof(accountId));if(initialBalance<=0)throw new ArgumentOutOfRangeException(nameof(initialBalance));var existing=await _ledger.ReadAccountAsync(accountId,token);if(existing.Any(x=>x.CommandId==commandId))return _projector.Project(existing);if(existing.Count>0)throw new InvalidOperationException("Sandbox account already exists.");var account=new SandboxAccount(accountId.Trim(),displayName.Trim(),"USD",initialBalance,_clock.UtcNow);await _ledger.AppendAsync([new(commandId,account.AccountId,null,"AccountCreated",_clock.UtcNow,account)],token);return await GetAccountAsync(account.AccountId,token);}
    public async Task<SandboxAccountState> CreateInstanceAsync(string commandId,string accountId,string instanceId,string strategyId,string strategyVersion,string instrumentId,string? contractId,CancellationToken token=default)
    {var replay=await ReplayAsync(accountId,commandId,token);if(replay is not null)return replay;var state=await GetAccountAsync(accountId,token);if(state.Instances.ContainsKey(instanceId))throw new InvalidOperationException("Sandbox instance already exists.");var strategy=await _strategies.FindAsync(strategyId,strategyVersion,token)??throw new KeyNotFoundException("Frozen strategy version was not found.");if(strategy.Status!=StrategyRegistryStatus.ValidationComplete)throw new UnauthorizedAccessException("Only validation-complete frozen strategy versions may enter the sandbox.");if(!strategy.Definition.SupportedInstrumentIds.Contains(instrumentId))throw new UnauthorizedAccessException("Strategy version does not support the requested instrument.");Definition(instrumentId);var instance=new SandboxInstance(instanceId,accountId,strategyId,strategyVersion,instrumentId,contractId,SandboxInstanceStatus.Created,_clock.UtcNow,null,null);await _ledger.AppendAsync([new(commandId,accountId,instanceId,"InstanceCreated",_clock.UtcNow,instance)],token);return await GetAccountAsync(accountId,token);}
    public async Task<SandboxAccountState> StartInstanceAsync(string commandId,string accountId,string instanceId,CancellationToken token=default)
    {var replay=await ReplayAsync(accountId,commandId,token);if(replay is not null)return replay;var state=await GetAccountAsync(accountId,token);var instance=Instance(state,instanceId);if(instance.Status!=SandboxInstanceStatus.Created)throw new InvalidOperationException("Only a newly created sandbox instance can start.");var updated=instance with{Status=SandboxInstanceStatus.Running,StartedAtUtc=_clock.UtcNow};await _ledger.AppendAsync([new(commandId,accountId,instanceId,"InstanceUpdated",_clock.UtcNow,updated)],token);return await GetAccountAsync(accountId,token);}
    public async Task<SandboxAccountState> SubmitSignalAsync(string commandId,string accountId,SandboxSignal signal,SandboxFillModel model,GovernancePermit permit,CancellationToken token=default)
    {var replay=await ReplayAsync(accountId,commandId,token);if(replay is not null)return replay;if(!_permits.Validate(permit,accountId,signal.InstanceId,signal.SignalId,_clock.UtcNow))throw new UnauthorizedAccessException("A valid governance permit is required for every sandbox signal.");var state=await GetAccountAsync(accountId,token);var instance=Instance(state,signal.InstanceId);var order=_broker.Submit(state.Account,instance,signal,model,_clock);await _ledger.AppendAsync([new($"{commandId}:governance",accountId,instance.InstanceId,"GovernancePermitAccepted",_clock.UtcNow,permit),new($"{commandId}:signal",accountId,instance.InstanceId,"SignalReceived",_clock.UtcNow,signal),new($"{commandId}:order",accountId,instance.InstanceId,"OrderSubmitted",_clock.UtcNow,order)],token);return await GetAccountAsync(accountId,token);}
    public async Task<SandboxAccountState> ProcessMarketAsync(string commandId,string accountId,SandboxMarketSlice market,SandboxFillModel model,CancellationToken token=default)
    {
        var replay=await ReplayAsync(accountId,commandId,token);if(replay is not null)return replay;var state=await GetAccountAsync(accountId,token);var definition=Definition(market.InstrumentId);var drafts=new List<SandboxLedgerDraft>{new($"{commandId}:market",accountId,null,"MarketObserved",_clock.UtcNow,market)};var available=market.AvailableQuantity;var positions=state.Positions.ToDictionary(x=>x.Key,x=>x.Value,StringComparer.Ordinal);
        foreach(var order in state.Orders.Values.Where(x=>x.InstrumentId==market.InstrumentId&&x.ContractId==market.ContractId&&x.Status is SandboxOrderStatus.Working or SandboxOrderStatus.PartiallyFilled).OrderBy(x=>x.SubmittedAtUtc).ThenBy(x=>x.OrderId,StringComparer.Ordinal))
        {var slice=market with{AvailableQuantity=available};var processed=_broker.Process(order,slice,definition,model,_clock);if(processed.Fill is null)continue;available-=processed.Fill.Quantity;drafts.Add(new($"{commandId}:order:{order.OrderId}",accountId,order.InstanceId,"OrderUpdated",_clock.UtcNow,processed.Order));drafts.Add(new($"{commandId}:fill:{processed.Fill.FillId}",accountId,order.InstanceId,"FillRecorded",_clock.UtcNow,processed.Fill));var key=SandboxStateProjector.Key(order.InstrumentId,order.ContractId);positions.TryGetValue(key,out var current);var projected=_portfolio.Apply(current,processed.Fill,definition);positions[key]=projected.Position;drafts.Add(new($"{commandId}:position:{processed.Fill.FillId}",accountId,order.InstanceId,"PositionUpdated",_clock.UtcNow,projected.Position));if(projected.Trade is not null)drafts.Add(new($"{commandId}:trade:{processed.Fill.FillId}",accountId,order.InstanceId,"TradeClosed",_clock.UtcNow,projected.Trade));if(available==0)break;}
        await _ledger.AppendAsync(drafts,token);return await GetAccountAsync(accountId,token);
    }
    public async Task<SandboxAccountState> CancelOrderAsync(string commandId,string accountId,string orderId,CancellationToken token=default)
    {var replay=await ReplayAsync(accountId,commandId,token);if(replay is not null)return replay;var state=await GetAccountAsync(accountId,token);if(!state.Orders.TryGetValue(orderId,out var order))throw new KeyNotFoundException("Sandbox order was not found.");if(order.Status is not(SandboxOrderStatus.Working or SandboxOrderStatus.PartiallyFilled))throw new InvalidOperationException("Only an open sandbox order can be cancelled.");var updated=order with{Status=SandboxOrderStatus.Cancelled};await _ledger.AppendAsync([new(commandId,accountId,order.InstanceId,"OrderUpdated",_clock.UtcNow,updated)],token);return await GetAccountAsync(accountId,token);}
    public async Task<SandboxAccountState> StopInstanceAsync(string commandId,string accountId,string instanceId,CancellationToken token=default)
    {var replay=await ReplayAsync(accountId,commandId,token);if(replay is not null)return replay;var state=await GetAccountAsync(accountId,token);var instance=Instance(state,instanceId);if(instance.Status!=SandboxInstanceStatus.Running)throw new InvalidOperationException("Only a running sandbox instance can stop.");var open=state.Orders.Values.Any(x=>x.InstanceId==instanceId&&x.Status is SandboxOrderStatus.Working or SandboxOrderStatus.PartiallyFilled);if(open)throw new InvalidOperationException("Cancel open sandbox orders before stopping the instance.");var updated=instance with{Status=SandboxInstanceStatus.Stopped,StoppedAtUtc=_clock.UtcNow};await _ledger.AppendAsync([new(commandId,accountId,instanceId,"InstanceUpdated",_clock.UtcNow,updated)],token);return await GetAccountAsync(accountId,token);}
    public async Task<SandboxAccountState> GetAccountAsync(string accountId,CancellationToken token=default){var events=await _ledger.ReadAccountAsync(accountId,token);if(events.Count==0)throw new KeyNotFoundException("Sandbox account was not found.");return _projector.Project(events);}
    public Task<IReadOnlyList<string>> GetAccountIdsAsync(CancellationToken token=default)=>_ledger.GetAccountIdsAsync(token);
    private async Task<SandboxAccountState?> ReplayAsync(string accountId,string commandId,CancellationToken token){var events=await _ledger.ReadAccountAsync(accountId,token);return events.Any(x=>x.CommandId==commandId||x.CommandId.StartsWith(commandId+":",StringComparison.Ordinal))?_projector.Project(events):null;}
    private InstrumentDefinition Definition(string instrumentId)=>_instruments.GetAll().SingleOrDefault(x=>x.InstrumentId==instrumentId)??throw new KeyNotFoundException("Instrument definition was not found.");private static SandboxInstance Instance(SandboxAccountState state,string id)=>state.Instances.TryGetValue(id,out var value)?value:throw new KeyNotFoundException("Sandbox instance was not found.");private static void Required(string value,string name){if(string.IsNullOrWhiteSpace(value))throw new ArgumentException($"{name} is required.");}
}

public sealed class SandboxControlAuthorizer
{
    private readonly byte[]? _expected;public bool IsConfigured=>_expected is not null;
    public SandboxControlAuthorizer(IConfiguration configuration){var token=configuration["Sandbox:ControlToken"];_expected=string.IsNullOrWhiteSpace(token)?null:SHA256.HashData(Encoding.UTF8.GetBytes(token));}
    public bool Authorize(string? supplied)=>_expected is not null&&!string.IsNullOrWhiteSpace(supplied)&&CryptographicOperations.FixedTimeEquals(_expected,SHA256.HashData(Encoding.UTF8.GetBytes(supplied)));
}
